import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white`}>
        <ul className="flex p-0 list-none">
          <li className="m-10">
            <Link href="/">Home</Link>
          </li>
          <li className="m-10">
            <Link prefetch={false} href="/users">
              Users
            </Link>
          </li>
        </ul>
        {children}
        <hr />
        <h1>this is footer</h1>
      </body>
    </html>
  );
}
